### ISSUE TITLE
Unable to prevent certain characters in input field

### ISSUE THREAD

**Issue by mistahenry** [ember-bootstrap/ember-bootstrap#1337] opened 2020-11-16 17:26 UTC
I'm having an issue in an app in which I try to catch the updating of a form-input and prevent certain characters from being allowed. Here is an [ember-twiddle](https://ember-twiddle.com/0c9a0b9be4278b8b72e28f5354303a3d?openFiles=controllers.application%5C.js%2C) showcasing my issue with a simplified version.  

I have a Bootstrap form in a route template

```hbs
<BsForm @formLayout="vertical" class="user" @model={{this}} @onSubmit={{this.onFormSubmit}} as |form|>
  <form.element class="d-flex align-items-center" @required={{true}}  @controlType="text" @property='username' as |el|>
    <el.control @placeholder="username" @onChange={{this.onUsernameChange}} class="form-control-user"/>
  </form.element>
  <BsButton @type="primary" type="submit" class="btn-user btn-block" data-test-submit-btn="true">Submit</BsButton>
</BsForm>
```

and I have a controller backing said template which uses the `onUsernameChange` action to prevent the letter `a` from being allowed in the input field :

```js
import Controller from '@ember/controller';
import { action } from '@ember/object';
import { tracked } from '@glimmer/tracking';

export default class ApplicationController extends Controller {
  appName = 'Ember Twiddle';
	
  @tracked
  username;

  @action
  onFormSubmit(){}
	
  @action
  onUsernameChange(newUsername){
    if(newUsername.length > 0 && 'a' === newUsername.charAt(newUsername.length - 1)){
      newUsername = newUsername.substring(0, newUsername.length - 1);
    }
    this.username = newUsername; 
  }
}
```

This doesn't seem to work. The `a` ends up being allowed in the input field if I type `a` twice. On the first iteration, `this.username` is updated from `undefined` to `""` which allows the `input` to re-render, removing the `a`. On the next type of the `a`, the `input` never updates, which I assume is due to no change in `this.username` since the value is assigned `""` again. Unfortunately, the `a` persists in the input.

If i were instead to use an input directly

```hbs
<input
    type="text"
    value={{@value}}
    {{on "input" @onChange}}
  >
```

with an action (passed to the component via `@onChange`):

```js
@action 
updateFoo(event){
  let value = event.target.value;
  if(value.length > 0 && 'a' === value.charAt(value.length - 1)){
    value = value.substring(0, value.length - 1);
  }
  this.foo = value;
}
``` 

then the `a` is always prevented from being entered into the field.

Just for completeness, the component is invoked like so:

```hbs
<FormInput @value={{this.foo}} @onChange={{this.updateFoo}}/>
```

Please see [this twiddle](https://ember-twiddle.com/495410d565f6d8a0ccd80241599b29e7?openFiles=controllers.application%5C.js%2Ctemplates.components.form-input%5C.hbs) for a working example

**Comment by jelhan** [comment] 2023-03-27 20:56
I cannot reproduce this issue anymore using the Twiddle you shared. At least in Firefox. I assume it has been fixed in the meantime. Somehow. Going to close this issue. If it has not been fixed, please come back.

**Closed by jelhan** 2023-03-27 20:56 UTC
