### ISSUE TITLE
CSS Variable issue with sass script execution

### ISSUE THREAD

**Issue by JackHowa** [ember-bootstrap/ember-bootstrap#1907] opened 2023-03-23 21:09 UTC
Output from `ember bootstrap:info`:

```
ember-bootstrap: ^4.9.0 -> 4.9.0
ember-cli: ~3.28.6 -> 3.28.6
bootstrap: 4.6.1 -> 4.6.1
bootstrap-sass: n/a
ember-cli-sass: ^11.0.1 -> 11.0.1
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
importBootstrapCSS: false
bootstrapVersion: 4
importBootstrapFont: false
```

Hello! It seems like this repo is really active so I appreciate any help. I'm working on using css variables to override bootstrap variables with interpolation. It's working as expected when I directly reference the value in scss. However, I'm getting an error in the integration with ember-bootstrap. I've tried removing importBootstrapCSS: false. I've also looked that `@import 'ember-bootstrap/bootstrap';` is included in the app.scss. Let me know if you have any ideas. I would expect for the interpolation to remain for the ember bootstrap, almost seems like a partial execution of the sass script.

```scss
$black: #{var(--__color-text-primary)};
```

source code of error in node modules: 

```scss
$popover-border-color:              rgba($black, .2) !default;
```

error 
```
Sass Syntax Error (SassCompiler) in /var/folders/qk/zg5xhbvj5v513jylrflswmxr0000gp/T/broccoli-9573GqOFZsaibB8B/out-1107-funnel_funnel_styles/ember-bootstrap/_variables.scss:905:37

Error: $color: rgba(var(--__color-text-primary), 0.2) is not a color.
    ╷
905 │ $popover-arrow-outer-color:         fade-in($popover-border-color, .05) !default;
    │                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  /var/folders/qk/zg5xhbvj5v513jylrflswmxr0000gp/T/broccoli-9573GqOFZsaibB8B/out-1107-funnel_funnel_styles/ember-bootstrap/_variables.scss 905:37  @import
  /var/folders/qk/zg5xhbvj5v513jylrflswmxr0000gp/T/broccoli-9573GqOFZsaibB8B/out-1107-funnel_funnel_styles/ember-bootstrap/bootstrap.scss 9:9      @import
  /var/folders/qk/zg5xhbvj5v513jylrflswmxr0000gp/T/broccoli-9573GqOFZsaibB8B/out-1107-funnel_funnel_styles/app/styles/app.scss 14:9                root stylesheet

```

**Comment by jelhan** [comment] 2023-03-25 21:18
Did you double checked that you are using the same Bootstrap version before and afterwards? And the same version of Ember CLI SASS? Is the error getting away if you use Ember Bootstrap but continue to integrate Bootstrap SASS in the build manually?

**Comment by JackHowa** [comment] 2023-03-27 02:36
Thanks for responding @jelhan. 

> Did you double checked that you are using the same Bootstrap version before and afterwards? 

I changed the variable overrides without upgrading or changing any dependencies. I'm not sure I follow but these are my dependency versions: 

```
ember-ui % npm ls bootstrap
└── bootstrap@4.6.1
npm ls ember-bootstrap
─ ember-bootstrap@4.9.0
```

> And the same version of Ember CLI SASS?

I didn't change the dependency either. I only changed the override value to use a SassScript with a css variable inside. 

```
ember-ui % npm ls ember-cli
├─┬ ember-cli-dependency-checker@3.3.1
│ └── ember-cli@3.28.6 deduped
└── ember-cli@3.28.6 
```

>  Is the error getting away if you use Ember Bootstrap but continue to integrate Bootstrap SASS in the build manually?

I'm not sure I follow. Can you explain how I would go about testing this? I'm updating the variable override in the bootstrap overrides file in one of the files that is manually updated in the `app.scss`. 

```html
<!-- index.html -->

<!-- toggle with media query -->
<style>
  --__color-text-primary: white;
</style>

```

```scss 
// app.scss
// Define Bootstrap variables and override with css variables
@import 'variables';

// ember-bootstrap import
@import 'ember-bootstrap/bootstrap';
```


```scss
// _variables.scss
$black: #{var(--__color-text-primary)};
```

**Comment by jelhan** [comment] 2023-03-27 07:06
Got it. I thought it was an issue introduced by migrating to Ember Bootstrap.

The error tells you that it's not a valid color.

```css
$black: #{var(--__color-text-primary)};
```

The `#` looks wrong to me. Could be caused by that. Or the Bootstrap utility does not support CSS custom properties. Support for those is still limited.

**Comment by jelhan** [comment] 2023-03-27 07:07
Going to close this issue as it's not related to Ember Bootstrap. StackOverflow might a good place for this question.

**Closed by jelhan** 2023-03-27 07:07 UTC
