### ISSUE TITLE
Cannot add ember-bootstrap to new ember app

### ISSUE THREAD

**Issue by trippetoe** [ember-bootstrap/ember-bootstrap#1868] opened 2023-02-16 18:16 UTC
When i add ember-bootstrap to a new ember app, the app does not load in the browser. The Google DevTools shows this error message in the console:
```
Uncaught TypeError: Cannot set property default of #<Object> which has only a getter
    at Module.makeDefaultExport (loader.js:88:1)
    at Module.exports (loader.js:114:1)
    at Module._reify (loader.js:143:1)
    at Module.reify (loader.js:130:1)
    at Module.exports (loader.js:104:1)
    at Module._reify (loader.js:143:1)
    at Module.reify (loader.js:130:1)
    at Module.exports (loader.js:104:1)
    at Module._reify (loader.js:143:1)
    at Module.reify (loader.js:130:1)
```

I can consistently reproduce this behavior. The simplest way to reproduce the behavior is 
1.  follow the initial steps described in the Ember [quick start guide](https://guides.emberjs.com/release/getting-started/quick-start/) to create a new ember app
2. at a command prompt in the app's folder enter `ember install ember-bootstrap`. 
3. once ember-bootstrap is installed, execute `ember generate ember-bootstrap --bootstrap-version=5`
4. verify that everything is installed correctly, e.g. verify in package.json that ember-bootstrap is included; verify ember-cli-build has a line(s) for ember-bootstrap; etc
5. execute `ember s`
6. open browser to http://localhost:4200

nothing loads, not even the Welcome Page

If i remove ember-bootstrap from the app using `npm uninstall ember-bootstrap --save-dev`, I can serve up the app's Welcome Page with no problems,

---

Output from `ember bootstrap:info`:

```
Npm packages:
ember-bootstrap: ^5.1.1 -> 5.1.1
ember-cli: ~4.7.0 -> 4.7.0
bootstrap: ^5.2.3 -> 5.2.3
bootstrap-sass: n/a
ember-cli-sass: n/a
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 5
importBootstrapCSS: true
```

**Comment by jelhan** [comment] 2023-02-16 22:34
This is a duplicate of #1865. It's a regression in ember-auto-import: https://github.com/ef4/ember-auto-import/issues/564 I hope they can fix it soon. For the time being, downgrading ember-auto-import is the recommended workaround.

**Closed by jelhan** 2023-02-16 22:34 UTC
