### ISSUE TITLE
[bs4-beta] active class not set on nav.item/nav.link-to when using willTransition

### ISSUE THREAD

**Issue by basz** [ember-bootstrap/ember-bootstrap#455] opened 2017-09-27 10:22 UTC
Hi,

I have a situation where I have a route with several child routes. The child routes are exposed with a tab. 
```
{{#bs-nav type="pills" as |nav|}}
    {{#nav.item}}
        {{#nav.link-to "account.identity.primary"}}{{t 'nouns.general'}}{{/nav.link-to}}
    {{/nav.item}}
    {{#nav.item}}
        {{#nav.link-to "account.identity.preferences"}}{{t 'nouns.preferences'}}{{/nav.link-to}}
    {{/nav.item}}
{{/bs-nav}}
```

Since the route 'account' is exposed in a navbar nav-link I created a redirect in its route to make sure `account.identity.primary` is loaded when the user clicks on that. This way child routes also add the 'active' class on that route for any child route.

To also make sure a user can also click on that nav link when he is on a different tab, I needed to add a willTransition. The redirect is only called when the route is first created.

 ```
import Route from '@ember/routing/route';

export default Route.extend({
  actions: {
    willTransition(transition) {
      if (transition.targetName === 'account.index') {
        transition.abort();

        this.transitionTo(`account.identity.primary`);
      } else {
        return true;
      }
    }
  },
  redirect: function (model, transition) {
    if (transition.targetName === `account.index`) {
      this.transitionTo(`account.identity.primary`);
    }
  }
});
```

This works almost perfectly, except the the active class is not set on the tabs when the willTransition transitionTo method is called. The route is loaded correctly. When I place simple {{link-to 'account.identity.primary'}} the tab is always set. The placement of that link-to does not matter (in the route, in any of its children or in a completely unrelated route.

```
Npm packages:
ember-bootstrap: kaliber5/ember-bootstrap#bs4-beta -> 1.0.0-rc.1
ember-cli: ^2.16.0-beta.1 -> 2.16.0-beta.1
bootstrap: ^4.0.0-beta -> 4.0.0-beta
bootstrap-sass: n/a
ember-cli-sass: ^7.0.0 -> 7.0.0
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
importBootstrapCSS: false
importBootstrapTheme: false
bootstrapVersion: 4
importBootstrapFont: false
```

**Comment by basz** [comment] 2017-09-28 12:49
a [movie](https://www.dropbox.com/s/a8mbamexhj7yr1k/tabs.mov?dl=0) might clarifies the issue perhaps

**Comment by jelhan** [comment] 2019-08-07 14:35
`{{nav.link-to}}` is deprecated. Should use `@route` and related arguments on `{{nav.item}}` instead. Implementation has changed a lot. @basz Are you able to reproduce with `{{nav.item}}` using latest release candidate for `v3`?

**Comment by jelhan** [comment] 2023-11-06 17:39
Closing due to missing reproduction.

**Closed by jelhan** 2023-11-06 17:39 UTC
