### ISSUE TITLE
btn-lg on vendor.css

### ISSUE THREAD

**Issue by yaxinr** [ember-bootstrap/ember-bootstrap#1777] opened 2022-03-24 09:21 UTC
For button
```hbs
<BsButton  @size='lg'   >qwe</BsButton>
```
when `importBootstrapCSS: true` then in vedor.css we have invalid order of styles
```
btn-lg{
  font-size:1.25rem
}
btn{
  font-size:1rem
}
```
and result is `font-size:1rem`

When `importBootstrapCSS: false`
and in ember-cli-build,js
```js
app.import('node_modules/bootstrap/dist/css/bootstrap.css')
```
then in vedor.css we have valid order of styles like in original bootstrap.css
```
btn{
  font-size:1rem
}
btn-lg{
  font-size:1.25rem
}
```
and result is `font-size:1.25rem`

---

Output from `ember bootstrap:info`:

```
Npm packages:
ember-bootstrap: ^5.0.0 -> 5.0.0
ember-cli: ~4.2.0 -> 4.2.0
bootstrap: ^5.1.3 -> 5.1.3
bootstrap-sass: n/a
ember-cli-sass: n/a
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 5
importBootstrapCSS: true
```

**Comment by jelhan** [comment] 2022-03-24 11:48
Thanks a lot @yaxinr for reporting this bug. Would be great if you could provide a reproduction as a public GitHub repo. This would help to investigate the issue quicker.

**Comment by jelhan** [comment] 2023-01-19 22:54
Closing due to missing feedback.

**Closed by jelhan** 2023-01-19 22:54 UTC
Labels: bug
